version: '2'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=dreams_prod
      - POSTGRES_PASSWORD=${DB_PASS}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  web:
    build: .
    command: bundle exec rails s -e production -p 3000 -b '0.0.0.0'
    environment:
      - SECRET_KEY_BASE=d5c0e5aa28800218042bc353b338ecc96b20b9d2a910ab08e374f0acaf2846fbe383638d6888108f7b3cf96034959ac5a853b6864b24eba99a19ee692531e25e
      - RAILS_ENV=production
      - RACK_ENV=production
      - DATABASE_URL=postgresql://postgres:${DB_PASS}@db/dreams_prod
    volumes:
      - .:/dreams
    links:
      - db
    ports:
      - '127.0.0.1:8090:3000'
    restart: always
