defaults: &defaults
  grant_value_for_currency: 2.64
  additional_info: true
  contact_phone: false
  description: true
  electricity: true
  light: true
  fire: true
  noise: true
  nature: true
  moop: true
  plan: false
  cocreation: true
  neighbors: true
  recycling: true
  budgetplan: true
  water: true
  seeking_members: true
  granting: true
  finace_messsage: true
  registration_requires_ticket_with_matching_email: <%= ENV['REGISTRATION_REQUIRES_TICKET_WITH_MATCHING_EMAIL'] or false %>
  add_to_list: true
  granting_active: true
  footer_text: true
  footer_logo: true
  creation_sidebar_welcome: true
  safetybag: false
  person_early_arrival: <%= ENV['PERSON_EARLY_ARRIVAL'] or false %>
  person_has_ticket: <%= ENV['PERSON_HAS_TICKET'] or false %>
  multi_lang_support: <%= ENV['MULTI_LANG_SUPPORT'] or false %>
  disable_open_new_dream: <%= ENV['disable_open_new_dream'] or false %>
  disable_edit_safetybag: <%= ENV['disable_edit_safetybag'] or false %>
  disable_edit_budget: <%= ENV['disable_edit_budget'] or false %>
  google_drive_integration: <%= ENV['GOOGLE_DRIVE_INTEGRATION'] or false %>
  show_point_of_contact: <%= ENV['SHOW_POINT_OF_CONTACT'] or false %>
  show_safety_file_comments: <%= ENV['SHOW_SAFETY_FILE_COMMENTS'] or false %>
  recaptcha: <%= ENV['RECAPTCHA'] or false %>
  max_grants_per_user_per_dream: 10

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
